name: Reddit Bot Agent CI/CD

on:
  push:
  pull_request:

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"
        
    - name: Set up Python
      run: uv python install
      
    - name: Install dependencies
      run: uv sync
      working-directory: ./agent
      
    - name: Login to GitHub Container Registry
      if: github.ref == 'refs/heads/master'
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Build and push Agent Docker image
      if: github.ref == 'refs/heads/master'
      uses: docker/build-push-action@v5
      with:
        context: ./agent
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/reddit-bot-agent:${{ github.sha }}
          ghcr.io/${{ github.repository_owner }}/reddit-bot-agent:latest
          
    - name: Build and push Scraper Docker image
      if: github.ref == 'refs/heads/master'
      uses: docker/build-push-action@v5
      with:
        context: ./agent
        file: ./agent/Dockerfile.scraper
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/reddit-bot-scraper:${{ github.sha }}
          ghcr.io/${{ github.repository_owner }}/reddit-bot-scraper:latest 