name: Reddit Bot Agent CI/CD

on:
  push:
  pull_request:

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"
        
    - name: Set up Python
      run: uv python install
      
    - name: Install dependencies
      run: uv sync
      working-directory: ./agent
      
    - name: Build Docker image
      run: docker build -t reddit-bot-agent .
      working-directory: ./agent
      
    - name: Login to GitHub Container Registry
      if: github.event_name == 'push'
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Tag and push image
      if: github.event_name == 'push'
      run: |
        docker tag reddit-bot-agent ghcr.io/${{ github.repository_owner }}/reddit-bot-agent:latest
        docker tag reddit-bot-agent ghcr.io/${{ github.repository_owner }}/reddit-bot-agent:${{ github.sha }}
        docker push ghcr.io/${{ github.repository_owner }}/reddit-bot-agent:latest
        docker push ghcr.io/${{ github.repository_owner }}/reddit-bot-agent:${{ github.sha }}
      working-directory: ./agent 